# **Homework 2: Introduction to Numpy**

### Name: Shayari Peiris
### Collaborator:


DATA 201A 

Fall 2022

Tufts University

## 1. Create a matrix

In [512]:
import numpy as np

#Row 1: Ten continuous integers from 1 to 10 in ascending order

row1 = np.arange(1, 11, 1)

In [513]:
#Row 1
#printing row1

print(row1)

[ 1  2  3  4  5  6  7  8  9 10]


In [514]:
#Row 2: Ten numbers from 0 to 45 with the same step size in ascending order

row2 = np.linspace(0, 45, 10, dtype=int)

In [515]:
#Row 2
#printing row2

print(row2)

[ 0  5 10 15 20 25 30 35 40 45]


In [516]:
#Row 3: Numbers from 1 to 20 with step size of 2 in ascending order

row3 = np.arange(1, 20, 2)

In [517]:
#Row 3
#printing row3

print(row3)

[ 1  3  5  7  9 11 13 15 17 19]


In [518]:
#Row 4: Make a copy of the first five numbers of Row 2. 
#Then make a copy of the first five numbers of Row 3. Concatenate the two copies together

#making an array with first five numbers of Row 2 (called "a")
a = row2[:5]
print(a)

[ 0  5 10 15 20]


In [519]:
#Row 4
#making an array with first five numbers of Row 3 (called "b")
b = row3[:5]
print(b)

[1 3 5 7 9]


In [520]:
#Row 4
#copying a as row4_part1
row4_part1 = a.copy()

In [521]:
#Row 4
#copying b as row4_part2
row4_part2 = b.copy()

In [522]:
#Row 4
#concatenating row4_part1 and row4_part2 to create row4
row4 = np.concatenate([row4_part1, row4_part2])

In [523]:
#Row 4
#printing row4

print(row4)

[ 0  5 10 15 20  1  3  5  7  9]


In [524]:
#Row 5: Sort Row 4 in descending order

row5 = np.sort(row4)[::-1]

In [525]:
#Row 5
#printing row5

print(row5)

[20 15 10  9  7  5  5  3  1  0]


In [526]:
#Row 6: Sort Row 4 but return the indexes of the sorted array **Rosie said to sort in descending order**

#sorting row 4 and naming new array as "row4_sorted"
row4_sorted = np.sort(row4)[::-1]
print(row4_sorted)

[20 15 10  9  7  5  5  3  1  0]


In [527]:
#Row6
#defining row6 as the index values of row4_sorted using arg.sort
row6 = np.argsort(row4_sorted)

In [528]:
#Row6
#printing row6

print(row6)

[9 8 7 5 6 4 3 2 1 0]


In [529]:
#Row 7: Make a copy of row 1. 
#Sum the numbers in Row 1 one by one and record the intermediate steps (accumulative sum) 

#making a copy of row1
#creating an accumulative sum of row1_copy and naming it row7
row1_copy = row1.copy()
row7 = np.add.accumulate(row1_copy)

In [530]:
#Row7
#printing row7

print(row7)

[ 1  3  6 10 15 21 28 36 45 55]


In [531]:
#Row 8: Make a copy of row 1. Broadcast +5 to every emelment in the array

#creating a copy of row1 and adding 5 to every element
row1_secondcopy = row1.copy()
row8 = row1_secondcopy + 5

In [532]:
#Row8
#printing row8

print(row8)

[ 6  7  8  9 10 11 12 13 14 15]


In [533]:
#Row 9: Same as row 1 but reverse the order of the last five numbers
#hint: consider sub_copy and concatination, the resulted array still has ten numbers

#creating a copy of row1
row1_thirdcopy = row1.copy()

In [534]:
#Row 9

#C = array that has the last five numbers of row1 in reverse order
C = row1_thirdcopy[10:4:-1] 
print(C)

[10  9  8  7  6]


In [535]:
#Row 9:

#D = array that has the first five numbers of row1 
D = row1_thirdcopy[0:5:] 
print(D)

[1 2 3 4 5]


In [536]:
#Row 9:

#concatenating rows C and D to create row9
row9 = np.concatenate([D, C])

In [537]:
#Row 9:
#printing row9

print(row9)

[ 1  2  3  4  5 10  9  8  7  6]


In [538]:
#Row 10: Same as row 1 but reverse the order of every other number (ex: only the 2nd, 4th, ... numberes are reversed)
#hint: consider using indexing to replace values, the resulted array still has ten numbers

#creating a copy of row1
row1_fourthcopy = row1.copy()
print(row1_fourthcopy)

[ 1  2  3  4  5  6  7  8  9 10]


In [539]:
#Row 10
#using indexing to replace every other value in reverse order

np.put(row1_fourthcopy, [1, 3, 5, 7, 9], [10, 8, 6, 4, 2])
print(row1_fourthcopy)

[ 1 10  3  8  5  6  7  4  9  2]


In [540]:
#Row 10
#naming row1_fourthcopy as row10 
row10 = row1_fourthcopy

In [541]:
#Row 10
#printing row10

print(row10)

[ 1 10  3  8  5  6  7  4  9  2]


2)Combine the 10 rows in 1) to a single array in sequence and form a 10x10 matrix

In [542]:
#Problem 2
#combining the 10 rows into a single array in sequence and form a 10x10 matrix

matrix = np.stack((row1,row2,row3,row4,row5,row6,row7,row8,row9,row10),axis=0)
print(matrix)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 1  3  5  7  9 11 13 15 17 19]
 [ 0  5 10 15 20  1  3  5  7  9]
 [20 15 10  9  7  5  5  3  1  0]
 [ 9  8  7  5  6  4  3  2  1  0]
 [ 1  3  6 10 15 21 28 36 45 55]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 1  2  3  4  5 10  9  8  7  6]
 [ 1 10  3  8  5  6  7  4  9  2]]


3)Use np.all or np.any to find the rows that only contain values below or equal to 10. Remove these rows.

In [543]:
#Problem 3
#creating a for loop to find any rows that only contain values < or = to 10 and appending the row index # to a list

drop_list = []

for i in range(len(matrix)):
    if np.all(matrix[i] <= 10) == True:
        drop_list.append(i)
        
print(drop_list)

[0, 5, 8, 9]


In [544]:
#Problem 3
#To do: remove rows 1, 6, 9 and 10

matrix_delete = np.delete(matrix, [drop_list], axis=0)
print(matrix_delete)

[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  3  5  7  9 11 13 15 17 19]
 [ 0  5 10 15 20  1  3  5  7  9]
 [20 15 10  9  7  5  5  3  1  0]
 [ 1  3  6 10 15 21 28 36 45 55]
 [ 6  7  8  9 10 11 12 13 14 15]]


4)For the new matrix you abtained in 3), reorder the rows in ascending order based on the sum of values in the rows. The resulted numpy array matrix will have first row with the largest sum and the last row with the smallest sum.

In [545]:
#Problem 4
#To do
#sum of elements in first row

#creating a for loop to find the sum of each row and appending the sums to a list called "sums"

sums=[]
for x in matrix_delete:
    sum(x)
    sums.append(sum(x))
print(sums)

[225, 100, 75, 75, 220, 105]


In [546]:
#Problem 4
#sorting the values in sums from smallest to largest

sums.sort()
print(sums)

[75, 75, 100, 105, 220, 225]


In [547]:
#Problem 4
#creating a new matrix with the row in ascending order according to sum

new_matrix = matrix_delete[np.argsort(matrix_delete.sum(axis=1))]

In [548]:
#Problem 4
#printing a new matrix

print(new_matrix)

[[ 0  5 10 15 20  1  3  5  7  9]
 [20 15 10  9  7  5  5  3  1  0]
 [ 1  3  5  7  9 11 13 15 17 19]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 1  3  6 10 15 21 28 36 45 55]
 [ 0  5 10 15 20 25 30 35 40 45]]
